name : Assignment-1
on:
  pull_request:
    branches:
      - feature/test
jobs:
  Build:
    runs-on: ubuntu-latest  
    # env:
    #  
    #   EXAMPLE_VARIABLE: ${{ secrets.EXAMPLE_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11' 
      - run: java -cp java HelloWorldApp