name: java app deployement
on:
  push:
    branches:
      - feature/varsha_assignment
#   pull_request:
#     branches:
#       - feature/varsha_assignment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

   
