name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
        name:
          description: "Caller of Reusable WF"
          type: string
          default: "assignment 2 "
jobs:
  calling-a-reusable-wf:
    uses: ./.github/workflows/reusable.yaml
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{secrets.ACCESS_TOKEN}}
    