name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "This is a caller wf"
jobs:
  calling-a-reusable-wf:
    uses: ./.github/workflows/reusable.yaml
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{secrets.ACCESS_TOKEN}}
    